[package]
name = "prophecy_roguelite"
version = "1.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
create_trader = "sozo execute prophecy_roguelite-actions create_trader --wait"
create_market = "sozo execute prophecy_roguelite-actions create_market --wait"
place_prediction = "sozo execute prophecy_roguelite-actions place_prediction --wait"

[dependencies]
dojo = "1.8.0"
starknet = "2.13.1"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.13.1"
dojo_cairo_test = "1.8.0"
